### ISSUE TITLE
Action bar is missing in a fresh codalab instance

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab#1008]
I checked out and installed the latest version of codalab and codalab-cli on Azure VM. The "Action Bar" is not present on the Worksheet page. Only the search bar is there. Are there any additional steps for setting up the "Action Bar" in the fresh instance of codalab?
thanks,
artem

**Comment by Raisins** [comment]
Hey @abmnv what branch are you on and do you have `worksheet_search.js` in your code base. Can you please also take a screen shot of the missing bar.

**Comment by abmnv** [comment]
Hi Raisins. I am on the master branch and the worksheet_search.js is present. 
![codalab_-_worksheets_-_2015-05-05_17 53 32](https://cloud.githubusercontent.com/assets/9452400/7483782/dc6511c4-f34f-11e4-9301-7257ae6c3f3e.png)

**Comment by Raisins** [comment]
You are on the worksheet list page. `/worksheets/` There are no worksheets. you need to create or talk to a worksheet via the cli. 
example `cl work http://localhostoryoursite:2800`  
Once you have worksheets they show up on that page and `/worksheets/0x4d2..UUID..944b1/` is what the worksheet url looks like.

**Comment by abmnv** [comment]
Is there a way to create worksheets using Action bar web interface? For example, I can create new worksheets on the official codalab website using web interface. Also, I noticed my search bar doesn't have "Go" button which is present on the official website. Are there any additional setup steps I need to do to get full functionality of Action Bar like on the official website? thanks.

**Comment by Raisins** [comment]
There is but you need to jump start it with the cli. We currently make the assumption that you are using the cli to start with. See `https://www.codalab.org/worksheets/0x8e7d56a12b31419fba6d5299830247be/` you can copy that to that instance to get you going with 
```
cl work http://localhostoryoursite:2800::
cl wcp http://yourlocalhostorsite:2800::<your-worksheet-name-from-prev-command> https://codalab.org/bundleservice::0x8e7d56a12b31419fba6d5299830247be
```

**Comment by abmnv** [comment]
ok, thanks it works.
