### ISSUE TITLE
better database backups

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1019]

**Comment by Raisins** [comment]
There is a monitoring script running with the cli that is doing light backups. 
https://github.com/codalab/codalab-cli/blob/7a9064eea0564b743af128929a41eb55ad5901e3/monitor.py#L140

**Comment by ckcollab** [comment]
Tx for info, will close this then!

**Comment by percyliang** [comment]
This currently doesn't backup the website db because the database is not
local.

**Comment by ckcollab** [comment]
What do you mean? Could it be extended to also backup the website database?
