### ISSUE TITLE
Add score display

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1020]
A score should be located on the public submissions panel, so users will know how good it is, and can verify it.

I put details below (see the last comment now), and here the checklist to them:

- [ ] 4.
- [ ] 5.
- [ ] 6. 
- [ ] 7.
- [ ] 8.

**Comment by ckcollab** [comment]
Reminder to self: you can probably store all computed scores and retrieve them much more simply... but could break all old views... maybe leave in legacy method and add in quick method?

**Comment by ckcollab** [comment]
What score should be displayed? The default sorted score?

**Comment by ckcollab** [comment]
- [ ] Overall score (default main sorted)
- [ ] Link to extended results
- [ ] Make "likes" column smaller
- [ ] Remove "likes" word from thumbs up/down
- [ ] Change "View (download count: 1)" to "<some download icon> (# of downloads)" eg, "<i> (23)"

**Comment by ckcollab** [comment]
Please test this on codalabtest

**Comment by lr292358** [comment]
I can see the scores of the first column and think it is OK -- we have the UI discussion in the other issue, thus I closed this one.

**Comment by lr292358** [comment]
It occurred that we closed this only because there was a misunderstanding between you and Isabelle. 
I assumed score == what people see on the leaderboard. But I specify here it in more detail:

We need to put scores (the accuracy on the dataset(s) ) that people see on the leaderboard (we can obtain the values e.g. form the scoring log) as subsequent columns. For the AutoML case, 5 columns with the scores. We do not need the average score at all (its OK to have it but it is computed based on the scores, no need to have it)

Comments:

  -  Description column (and other) should be not too wide (to fit 5 scores columns).
  -  Would be good to be able to sort by a selected column (if not too hard to do it)

**Comment by ckcollab** [comment]
Do not show average rank

**Comment by lr292358** [comment]
(average rank is computed -- not in the scores.txt)

I need to be able to choose which columns to be displayed -- to make it simply, let's omit all columns after the 'Duration'.

**Comment by lr292358** [comment]
I put details above, and here the checklist to them:

- [ ] 4.
- [ ] 5.
- [ ] 6. 
- [ ] 7.
- [ ] 8.
