### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1021]
add “likes/dislikes” (vote) at particular submission in public submissions and display the number of thanks.
A user can give only one like/dislike to a submission.

**Comment by ckcollab** [comment]
Merged to codalabtest for testing

**Comment by ckcollab** [comment]
Ideas for improving UI:
- Thumbs up icon?
- Add ability to thumbs down/dislike
- Hovering show # of up vote/down vote
- Show overall "score" Likes - dislikes
- (reminder for myself) GGGamers thumbs up/down green/red buttons

**Comment by lr292358** [comment]
I checked and it worked, now we wait for a new version with thumbs in which will be more to test.
