### ISSUE TITLE
Editing submissions comments.

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1022]
Editing submissions comments (after the actual submission).

For example a user submitted a code, and saw that the result on the validation dataset was great. 
Thus decides to share, now the user wants to add some description for other participants, so they know what it actually contains.

**Comment by ckcollab** [comment]
Submission comments == submission description

**Comment by lr292358** [comment]
Very important -- I actually never filled it while submitting.

**Comment by lr292358** [comment]
Out of all new features, this is of the highest priority.

**Comment by lr292358** [comment]
I tested and it works, there are 2 fixes needed regarding UI:

a) when you click 'update' a textfield with the current comment should appear/be enabled and a save button also should appear/be enabled.
Currently, when you have a comment and you want to update -- I click update, and it disappears and is overwritten with empty comment. I wanted to edit, but it was lost.
Also clicking the button by accidence will remove the text and save empty comment immediately.

When you start editing, a current comment should be put to the textfield (to actually edit/add something)

b) I can see in my preview the html tags work, like I can do <br>, <ul><li> .. etc.
But html tags do not work in the public submissions panel. I think they shouldn't appear at all (display html tags as normal words in the preview).

**Comment by lr292358** [comment]
Putting to test. That could be done also with just one button -- when you click update, the comment could be copied to this textfield, and the name of button change to save, then it would be saved when clicked.
