### ISSUE TITLE
Optimize slow pages

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1026]
- [x] Admin view submissions page
- [ ] Participate page for a competition (submit results page)
- [ ] Participants page
- [x] Competition list (double check slowness here)

**Comment by lr292358** [comment]
Out of these 3, two are actually very slow -- the submissions and participate page. Competitions list is OK even if I have a large number of competition.

It takes about 20 seconds to see the AutoML competition page (= participate, so for every user, not admin, this must be faster (why is it slow? -- reading ranking in not included in this time)), and 30 seconds to load submission. So if you want to see submissions, firstly you wait for a page (30s) and then next 30s for submissions from a phase you select, total over one minute to see.
