### ISSUE TITLE
Stdout/err logs of the last seconds of execution are lost

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1047]
Last part of out are lost. It also happens with the -u flag.

This is very important:
I had no output in the scoring program (added sleep at the end to workaround).

Output of users codes/runtime errors before crash might not be stored.

This was the problem when I was testing one feature earlier -- there was a problem, but errors were not stored, so didn't know what happened and couldn't test.

**Comment by ckcollab** [comment]
Pushing this to codalabtest for testing

**Comment by lr292358** [comment]
now OK, closed.
