### ISSUE TITLE
side panel rendering of fields delayed

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1061]
When focus on a current item, the side panel updates with some fields, but date/memory fields are first rendered as integers, and then a second later rendered properly as a string (e.g., 32M).  The correct render should happen from the start.

**Comment by Raisins** [comment]
this is a cli change, the formatting happens on the backend before is sent over on the details call.

**Comment by percyliang** [comment]
I assume the initial rendering is based on the results of
get_worksheet_info.  This should still be rendered.

**Comment by ErickWa** [comment]
Blocked by CLI updates

**Comment by percyliang** [comment]
Fixed.
