### ISSUE TITLE
Improve competition usability (again)

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1075]
I put here two small very important things that were therefore written in the comments ( #1005 #989 ), but were lost in the meantime.

- [x] add a link to edit a competition on the competition, so to 'competitions/edit_competition/ID'

currently you need to click competitions, competitions I'm running, and find a competition in the list, which is hard if you have a lot of duplicates, it is very inconvenient.

- [x] on the public submissions panel, display the number of downloads. We have the number of downloads already calculated, just we need to show it to people.

**Comment by lr292358** [comment]
Hi Eric, when this is done, please push this and the competition sorting feature to codalab so we have it there.

**Comment by ckcollab** [comment]
Thank you very much for pulling this into a new issue, will get to this ASAP
