### ISSUE TITLE
[!] Global error with stdout

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1081]
All submissions fail.
On codalabtest:

Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 340, in run
    _upload(blob_service, container, stdout_id, stdout_file)
NameError: global name 'stdout_file' is not defined

On codalab - now OK for me, participants reported this:
There was an error retrieving file 'predict_stdout.txt'. Please try again later or report the issue

**Comment by ckcollab** [comment]
Should be fixed let me know if not!
