### ISSUE TITLE
Bug: you can download an unshared submission

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1083]

**Comment by ckcollab** [comment]
How are you doing this? From the "Public Submissions" view or what? As logged in user? As non logged in?

**Comment by lr292358** [comment]
I shared and unshared as one user on codalabtest, then logged in (I had to be logged in) as other user and was able to download.

**Comment by ckcollab** [comment]
So even after unsharing it remained in the public submissions view?

**Comment by ckcollab** [comment]
Btw, was the other user you were logged in as, an owner/admin of the competition?

**Comment by lr292358** [comment]
I meant that you still can download. It disappears from the view (but not if you have a page open and do not refresh), but you can still access by the link. Link can be deducted, can be also put on forum, etc. I shared as admin and other user was not.

**Comment by ckcollab** [comment]
Alright, thanks, I believe this is fixed now, marking as test.

**Comment by lr292358** [comment]
now OK, removed test label
