### ISSUE TITLE
Public submission UI improvements

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1092]
- [x] Make the public submission description truncate after 2 lines (~150 characters??)
- [x] have a "Read more" link after, if truncated
- [x] Add link for detailed results
- [x] Make "likes" column smaller
- [x] Remove "likes" word from thumbs up/down
- [x] Change "View (download count: 1)" to `"<some download icon> (# of downloads)"` eg, `"<i> (23)"`

**Comment by lr292358** [comment]
I updated the details after talking with Isabelle, this is mainly about adding score columns.

**Comment by ckcollab** [comment]
As this has already been merged please put new changes in a new issue

**Comment by lr292358** [comment]
Part 1 OK, I closed
