### ISSUE TITLE
new action bar doesn't work in Linux Firefox or Chrome

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1096]
When type random things, error message is printed fine.

If type any real commands (e.g., 'cl help'), the action bar state gets messed up, the cursor disappears.

In the JS console, get:
POST http://codalabtest.cloudapp.net/api/worksheets/command/ 401 (UNAUTHORIZED)
ws_actions.js:9 Uncaught TypeError: Cannot read property 'error' of undefined

**Comment by Raisins** [comment]
error with logging of error.
