### ISSUE TITLE
UI improements extension

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1100]
We need to put scores (the accuracy on the dataset(s) ) that people see on the leaderboard (we can obtain the values e.g. form the scoring log) as subsequent columns. For the AutoML case, 5 columns with the scores. We do not need the average score at all (its OK to have it but it is computed based on the scores, no need to have it)

Comments:
- Description column (and other) should be not too wide (to fit 5 scores columns). 
- Would be good to be able to sort by a selected column.

**Comment by ckcollab** [comment]
I don't think it's a good idea to add all of the columns...? it will increase complexity significantly and I'm supposed to be moving onto stabilization issues.

I don't think we'll need to truncate usernames?

I can do the date format change, but in my opinion that's the last change we should do for the UI at this point.

**Comment by lr292358** [comment]
Isabelle suggested the date format was only to save space when we have columns, columns are a good idea and that was an idea since the very beginning, and I discussed with Isabelle. We just need to show the values from scores.txt -- currently people need to download the .zip archive and unpack it for each submission -- cannot answer a questions like: which submission is the best for that dataset? 

I think you can move to stabilisation and do our things in the meantime. We have only 2 items left: editing submissions descriptions & UI improvement, it's not needed for today -- 22 June would be fine.
Submitting worksheet is cancelled, so one big task less.

**Comment by lr292358** [comment]
Is it easy to do sorting by a specific column?

**Comment by ckcollab** [comment]
Re: displaying all columns, ok, we can add that in (it was my understanding 1 column would work). Sorting will be difficult, probably, I can look for plugins to help.

**Comment by lr292358** [comment]
We can sort the ranking in the leaderboard so I thought maybe you can reuse it -- please try to see how you can do it with that or the plugins you mentioned, if it's a lot to do then let's go firstly with just displaying the values and discuss that later during the meeting.

**Comment by lr292358** [comment]
==========

Actually, I reduced this UI issue only to the proper understanding of the earlier issues -- closing this one then.
