### ISSUE TITLE
action bar: clhist <bundle> should put the command into the action bar history

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1106]
clhist <bundle> should do a
cl info -f args <bundle>
which prints out a string.
This string should be appended to the history, so that <up arrow> should recall that command.

**Comment by Raisins** [comment]
cl info -f args ^X

**Comment by percyliang** [comment]
Update: we should have a keyboard shortcut that copies the command of the current bundle into the web terminal (just like we will for the bundle uuid).  Perhaps we should have a tiny link in the side panel that does this too.

**Comment by percyliang** [comment]
This was addressed by #1376
