### ISSUE TITLE
Submissions > max submissions allowed (e.g. 24 with 5 limit in AutoML)

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1119]

**Comment by lr292358** [comment]
In general the feature worked for me. 
"actually boasted about it on the forum"
where can I view the details?

**Comment by lr292358** [comment]
Here was the topic, we didn't understand what he tried to say and everything is OK, so I close https://groups.google.com/forum/#!topic/automl/KbU8XQOo7h0

**Comment by lr292358** [comment]
I sent on email a log, indeed they did 24 submissions on one day, and also other teams. I tested it in other competition and everything worked, but it does not work in the AutoML...

**Comment by lr292358** [comment]
This is P1 of course

**Comment by ckcollab** [comment]
Francis looked into this, looks like it's not an actual problem? (he looked over the list of all valid submissions in each phase and none had > 5 in a day)
