### ISSUE TITLE
Redirects for competitions

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1126]
http://codalab.org/Age should re-direct to https://www.codalab.org/competitions/4711
 
http://codalab.org/Caption should re-direct to https://www.codalab.org/competitions/3221

**Comment by Raisins** [comment]
why DNS? Why not just create simple one off views that do a 301 in Django. We can then edit add as needed. If this is a one or two off thing, or even a 4 or 5 off thing, lol.

**Comment by ckcollab** [comment]
Sorry that was unclear, that's how it will be done. (just like AutoML was)
