### ISSUE TITLE
View compute worker logs

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1128]
Logs from compute workers should be visible on some kind of admin interface in production.

**Comment by ErickWa** [comment]
May be completed. Flavio, please record the URL here.

**Comment by ErickWa** [comment]
http://codalabtest-py3.cloudapp.net:8000/?pass=codalab-rules

**Comment by ckcollab** [comment]
Hey sorry, had to pull that URL off there, had sensitive information at the end of the URL, maybe record that somewhere else?

**Comment by ckcollab** [comment]
`http://codalabtest-py3.cloudapp.net:8000/?pass=<THE PASSWORD>`

Maybe like that? And save password elsewhere? Hope all is well!

**Comment by ErickWa** [comment]
No worries.  Flavio, can you store the appropriate Admin password in the Dropbox Credentials file?

**Comment by FlavioAlexander** [comment]
@ckcollab Thank you, all good so far. @ErickWa I will. I think we can close this issue again :)

**Comment by FlavioAlexander** [comment]
Added in bitbucket repo
