### ISSUE TITLE
Competition: Participate: Phases should prompt user toward the end of current and start of the next. 

### ISSUE THREAD

**Issue by MedicalTest** [codalab/codalab#113]
Issue:  Competition: Participate: Phases should prompt user toward the end of current and start of the next. 

Steps:
     1.  Launch CodaLab  (http://codalab.org)
     2.  Sign in to a competition for which your acceptance has been granted.
     3.  Attempt to submit results after Phase One has passed.

Actual result:  User is unable to submit results.

Expected result:  User should have explicit visual reinforcement of where they are in the competition. This issue was exposed in a recent demo where Phase One ended at midnight, Aug 22nd.

Configuration details
Build date: 8/22/2013, ~10 a.m.
OS: Win7
Browser(s):   all supported

**Comment by ErickWa** [comment]
Needs user story; related to #849

**Comment by ErickWa** [comment]
Related to #473
