### ISSUE TITLE
links to predict outputs are swapped

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1142]
'View predict error log', 'View predict output log' are swapped -- stderr is stdout, and stdout is stderr :)

**Comment by ckcollab** [comment]
Where is this error? they appear to be right to me?

**Comment by ckcollab** [comment]
I believe this is not a problem??

**Comment by lr292358** [comment]
This is a problem, I often open outputs and it is confusing. 
If it is a problem to solve it, let's then do a workaround temporarily and change the links:
So the 'stdout' goes to 'stderr.txt'

**Comment by ckcollab** [comment]
I'll do some more testing today to determine whether outputs are getting swapped, could be the scoring program or something?

**Comment by lr292358** [comment]
no... the scoring program has own stdout/err links. It is not related, these are outputs from executing the code. They are swapped while executing on workers. 

Probably run.py 1>stderr.txt 2>stdout.txt instead
run.py 2>stderr.txt 1>stdout.txt
