### ISSUE TITLE
Display max number of submissions per day & total

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1145]
Small feature: people want to know the limits and they wrote to us that limit was surprising them-- we need to show the limits of the given phase to them -- so it will be visible in all competitions on codalab.

**Comment by madclam** [comment]
The limit is 5 submissions per day. It has been the same in all Tweakatons and is documented in the instruction. HOWEVER there may be a bug: I noticed in the previous Tweakathon that one guy made a suspiciously large number of submissions and actually boasted about it on the forum saying that the max number should be enforced. Please check with Eric that all is well.
Best,

Isabelle

**Comment by lr292358** [comment]
Hi, I do not refer to AutoML, I am talking about all competitions on codalab like NIPS, KDD etc and the numbers might change and we do not want to update pages each time.
We need to show it, that's good it is documented somewhere, but it need to be clear and also in all competition.

**Comment by ckcollab** [comment]
- [ ] Add max per day, max total underneath "Phase Description"
