### ISSUE TITLE
Anonymous leaderboard

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1151]
- [x] Add flag to competitions `anonymous_leaderboard`
- [x] When flag is active hide all usernames from leaderboard
- [x] Highlight your place on the leaderboard, this will be useful even not in `anonymous_leaderboard` mode

**Comment by lr292358** [comment]
I thought it is already possible since automl2 results are hidden, please tell us.

**Comment by ckcollab** [comment]
No this is a different feature. This is just hiding usernames but still displaying scores.
