### ISSUE TITLE
Important fixes in public submission panel

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1154]
Here is a list of small problems. Below 2 screens (public submission panel and original results leaderboard), plus a link to the competition.

Issues:
- [ ] Description field has no characters in one line limit -- any link etc will destroy the UI, as in the screen.
I suggest: Taking max 3 lines from the description, and cutting each line after 20 characters
- [x] The columns vs results are shifted: Set 1 has no score, it's score is in Set 2
- [ ] There is a 'Score' column with 0E-10 value, I do not where this column/value comes from.
- [ ] automatically refresh page while clicking 'Public submissions' panel -- very important, everybody has problems with that now
- [x] Display 4 digits, like 0.4124, not whole long numbers
- [ ] Display integer 2 as 2, not 2.0000000000, maybe preprocess with 
   "x = (x == round(x)) ? round(x): x;"
- [ ] add an hour hh:mm to the submission time (a year is optional).
- [x] enable sorting for the scores column

Screens
![ps](https://cloud.githubusercontent.com/assets/4463818/8696376/1100f672-2aec-11e5-9ed1-eba46e087157.jpg)
![lb](https://cloud.githubusercontent.com/assets/4463818/8696248/141de00a-2aeb-11e5-87a9-69f0a845609c.jpg)
Scores.txt (line 9 is empty, so should not be treated as score)
![sco](https://cloud.githubusercontent.com/assets/4463818/8696804/f0b98ab0-2aef-11e5-8d9e-c9a51e3e420c.jpg)

Competition:
http://codalabtest.cloudapp.net/competitions/1030?secret_key=8470a85d-1b26-4579-b44f-d898c4a3e0d3

**Comment by ckcollab** [comment]
I'm closing this right now and maybe picking up the most important parts in a batch of new issues.
