### ISSUE TITLE
Phase migration

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#1207]
Misc problems with migration:

1) Old jobs that were still in "running" mode prevented the phase transition. Need diagnosis:
 .  mark the time when a job was started. 
 . track to which compute worker the job was send 
 . indicate whether a worker is presently running.
Use a job garbage collection: After the twice the max time is exceeded the job should be killed.  Need a "restart" button to manually restart.

2) The number of jobs launched exceeded the number of compute workers. This should never happen since we want a compute worker to be dedicated to a given job until the job is terminated.

3) The phases transition started before all jobs were executed in the previous phase.

4) In Secret url: http://codalab.org/competitions/5211?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35, though everything seems to have been computed in AutoML 1.5, the phase did not finish migrating and the leaderdoard did not appear.

**Comment by ErickWa** [comment]
Updating spec to include "hidden" phase migration

**Comment by ErickWa** [comment]
@madclam may we close this issue based upon @ckcollab 's test results?

**Comment by ErickWa** [comment]
Item #1 is still open, #2-4 are addressed
