### ISSUE TITLE
Hide result from leaderboard

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#1231]
We would like the organizers of a particular competition to have the authority to force entries to be hidden or shown on the leaderboard (and thus be taken into consideration in the computation of the leaderboard scores) **for a given phase**. This action should be reversible (this is NOT a delete action).

Currently, we have a panel called submissions with a "DEL" and a "FAILED" button:
![image](https://cloud.githubusercontent.com/assets/7594063/9458550/7a2e6b5c-4aa4-11e5-9acd-aa01a884b1a1.png)

We would like another button called "HIDE" (which would toggle with "SHOW") with the following effet:
- On "HIDE", 
      if the submission is marked as "Status: Running" or "Status: Failed" or "Leaderboard: False" => no effect
      submissions marked as "Status: Finished" and  "Leaderboard: True" => change to "Status: Finished" and  "Leaderboard: False" (it is OK to have all the entries of a participant hidden, do NOT automatically enable the second last "Finished" entry).
- On "Show"
      if the submission is marked as "Status: Finished" and  "Leaderboard: True" => no effect
      if the submission is marked as "Status: Finished" and  "Leaderboard: False" => change to "Status: Finished" and  "Leaderboard: True" (Since we cannot allow multiple entries of the sample participants in the leaderboard, automatically hide any other entry of this participant previously shown on the leaderboard).

**Comment by ckcollab** [comment]
Thanks for the very detailed spec! will get this done today hopefully
