### ISSUE TITLE
Receive an email notification when a new result appear in the leaderboard

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab#1233]
Feature request: as a competition participant, it would be nice to have an option allowing me to receive an email notification whenever a new result appears in the leaderboard (even better if it was possible to condition the notification on some threshold on the metric(s) used in the leaderboard, e.g. get notification iff new result with > 0.9 F1-score).

**Comment by ckcollab** [comment]
Could we re-purpose this issue to sending an email notification upon completion of any submission evaluation?

What should the email contain? Something like:
- Submission file name
- Submission score
- Submission execution time

**Comment by ckcollab** [comment]
Notify options:
- Per competition? Put checkbox next to submit button
- Per user? Put checkbox in profile page
