### ISSUE TITLE
display more information about subworksheets

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1241]
Suppose we're viewing a worksheet containing many subworksheets.  When we mouse over them, the side panel should contain basic information about those subworksheets (owner, title).  The actual rendering of the subworksheet on the page should also have the title in addition to the name (but take up no more vertical space).

**Comment by Raisins** [comment]
Currently showing all the info that is given via the api. What else should be showing about worksheets in side worksheets
API
<img width="333" alt="screen shot 2015-09-26 at 3 57 01 pm" src="https://cloud.githubusercontent.com/assets/123099/10120252/63729640-6467-11e5-9f33-2f4654e113f5.png">
Display
<img width="332" alt="screen shot 2015-09-26 at 3 57 14 pm" src="https://cloud.githubusercontent.com/assets/123099/10120253/697fb996-6467-11e5-829e-4bf4b1a524c8.png">

**Comment by percyliang** [comment]
For the main worksheet, display all that you get including title and frozen
(need to test with worksheets for which this is not null)

For subworksheets inside a worksheet (which this issue is about), should
display:
[name: title]
in the worksheet body.
When people focus on it, the side panel should display all the other
information (e.g., frozen, owner etc.)

**Comment by Raisins** [comment]
Display title in worksheet bundle.
