### ISSUE TITLE
Change and upgrade azure service bus. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab#1243]
Do to recent changes and updates. New services busses do not accept ACS credentials. We need to upgrade the package and move to SAS credentials.  This may cause other problems in production and test. 

http://blogs.msdn.com/b/servicebus/archive/2014/09/03/change-to-azure-service-bus-portal-default-authentication-mechanism-for-service-bus-namespaces-now-sas.aspx

https://pypi.python.org/pypi/azure

https://github.com/Azure/azure-sdk-for-python/blob/c9e800cb3d72516403d4be9ce1b88b32e149b3fa/azure-servicebus/azure/servicebus/servicebusservice.py#L78

This is currently blocking local dev, for now we are able to piggy back on legacy services buses from testevn. We discovered this when 3rd party azure account got shut down and needed to move to proper codalab account.

**Comment by Raisins** [comment]
We may want to reopen this. @ckcollab These changes are for good and the only way to create a bus is with the command line tool. We should upgrade to the new system.

**Comment by ckcollab** [comment]
I'll put it in the wiki, and I think you got it backwards we needed ACS and NOT SAS? Or am I getting it backwards?

**Comment by Raisins** [comment]
"Default Authentication Mechanism for Service Bus Namespaces now SAS" We should probably support SAS as default as well. Rather then obscure doc lookups and command line tricks.

**Comment by ckcollab** [comment]
When are they removing ACS? Installing the cli was a breeze, if they aren't removing it soon then I vote we put it off.

**Comment by ckcollab** [comment]
From mentioned article: "Are we moving away from ACS?
No! ACS is still fully supported in Service Bus and will be for the foreseeable future.  As Azure Active Directory (AAD) expands to support more service federation identity scenarios we will increasingly align with the AAD service offering. "

So I'm closing this, I documented how to create the service bus extra-clearly so it should be ready to go!
