### ISSUE TITLE
Unnecessary indentation of stdout/stderr @bundle details page

### ISSUE THREAD

**Issue by tonyyang1993** [codalab/codalab#1250]
In stdout/stderr preview of a run bundle, starting from the second line, there is always an extra space.

Reference links:
stdout: https://www.codalab.org/bundles/0xca09c8e2318349a2b996de9c54e2f914/
stderr: https://www.codalab.org/bundles/0x78c722b0e1994d5c91f43a293ef9ca71/

**Comment by Raisins** [comment]
@tonyyang1993 saw this reopen, Update the less not the css. It gets compiled and replaced.
