### ISSUE TITLE
on markdown, side panel should show empty

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1251]
Currently, side panel shows list of bundles on the page, which is confusing.
Instead, just show empty.

**Comment by Raisins** [comment]
This is showing the default worksheet info. Since no data belongs to a markdown. The thought was give them another way to see worksheet info rather then not having anything selected. Also having some info is better a blank side panel.

**Comment by percyliang** [comment]
We can have the full info view when the focus is not on any worksheet item
(i.e., when the page first loads), but if the focus is on a markdown item,
the side panel should be empty.
