### ISSUE TITLE
url to access worksheet by name

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1256]
Something like:
http://codalab.org/worksheets?name=executable-papers

Note that this is not a stable URL.

**Comment by percyliang** [comment]
What is the URL to use this feature?
/worksheets?name=pliang doesn't work

**Comment by Raisins** [comment]
This does work on test env right now. Pushing to prod later

**Comment by percyliang** [comment]
Question remains.  I'm trying this out locally given your new changes.
