### ISSUE TITLE
Submission list out of order

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1261]
![image](https://cloud.githubusercontent.com/assets/2185159/9767703/52b3bb86-56d4-11e5-8b6e-079654baaf22.png)

Starts at 5 instead of one?

**Comment by madclam** [comment]
The order in the participant's submission panel is messed up. We received several complaints. Here is the last one: 
On Sep 14, 2015, at 6:38 AM, Kocheganov, Victor M <victor.m.kocheganov@intel.com> wrote:

Dear organizers,
 
Recently I tried to submit new results to Tweakathon2, and realized very confusing sorting rule: I can hardly find my last (by date) submission to check it.
Is there any possibility to add an option to sort by date?
 
Thank you in advance,
Kocheganov Victor (asml.intel.com)
