### ISSUE TITLE
Add preview when bundle is a single file

### ISSUE THREAD

**Issue by tonyyang1993** [codalab/codalab#1269]
Reference bundle:
https://www.codalab.org/bundles/0x7665d99ca3724747a10ae443cd0c90d6/

The bundle is a simple text file. At website interface, we'd better provide a preview of this file, like what we did for stdout/stderr. At command line interface, `cl cat uuid` does a great job.

**Comment by percyliang** [comment]
Need to do this in both the side panel and the bundle details page.
