### ISSUE TITLE
Running any command fails, citing a TLS error

### ISSUE THREAD

**Issue by arunchaganty** [codalab/codalab#1288]
I tried to run "cl run 'ls'" from both the command line and the web interface and received the following error message:

time="2015-09-25T16:41:14-07:00" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/containers/50a9c8edba4b3e5895feddcbf66e12e257bd68049aee5f746ee26ddcacf583e2/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?"

**Comment by percyliang** [comment]
The problem is that docker is kind of broken on CentOS (version 6.6) -
works fine on Ubuntu.  Affects only the jude machines; setting default to
john, so it should work now.

 -Percy
