### ISSUE TITLE
Hidden phase migration

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1306]
On phases where `auto_migration` is enabled, automatically submit submission to next phase.

TODO think about this: **We'll need to remove current auto migration behavior or have some flag to disable it, or a new flag instead of replacing `auto_migration` maybe `auto_migration_ahead_of_time`**

Only migrate +1 phase, do not do subsequent phases. As in, if you are in phase 1 and have automigration for phase 2 and 3, only pre-migrate to phase 2 not 3.

Bonuses:
- [ ] Mark submission with "warning" if it fails in the next phase

**Comment by FlavioAlexander** [comment]
@ckcollab What do you mean by "Only migrate +1 phase, do not do subsequent phases. As in, if you are in phase 1 and have automigration for phase 2 and 3, only pre-migrate to phase 2 not 3."

**Comment by ckcollab** [comment]
Bingo

**Comment by ckcollab** [comment]
To clarify: this is to potentially depreciate auto migrations by doing them as people submit to the previous phase, instead of submitting everything in bulk at the end of the phase.

Also, should probably add a flag to each submission like `has_been_hidden_migrated`. So if someone enables this flag on a competition phase that already exists and the previous phase already has submissions, they will be migrated once and marked `has_been_hidden_migrated`.

**Comment by FlavioAlexander** [comment]
Potential option to reduce tons of submissions being migrated needlessly is to only migrated submissions on leaderboard

**Comment by FlavioAlexander** [comment]
@madclam is this something we really want? I am just debating with this scenario. For instance::

* A competition with multiple phases and 5 participants
  * If phase 2 "auto_migration=True". If all 5 participants submit multiple submissions on phase 1. Do we want all of them to be migrated to phase 2? 

Best,

Flavio

**Comment by ErickWa** [comment]
Need more guidance from @madclam before proceeding
