### ISSUE TITLE
Competition Ordering

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#1307]
Should move competitions with no end date to the bottom

- [ ] Ordering for personal competition page
- [ ] Ordering for anonymous competition page
- [ ] BONUS: Abstract away personal/anonymous separate functions, instead have a "Get Competition List" function that both views call, then we can test just that function without having to do any `self.client.get` stuff!

**Comment by ErickWa** [comment]
We have some corner cases here that may not be worth closing out. @madclam , can you review and let us know if we can close this?

**Comment by FlavioAlexander** [comment]
- We have two different columns now. One for popular competitions, and one for featured/new competitions.
