### ISSUE TITLE
MISSING field values in worksheet are somewhat inconsistent

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab#1336]
In worksheet tables, some field values are marked as MISSING, but the criteria for showing MISSING instead of a blank cell is somewhat inconsistent.

```
% add mem1 memory
% add mem2 memory size
% add mem3 memory %d
% add mem4 memory s/0/z
% add mem5 memory "%s | s/0/z"
% add |
```
![scr](https://cloud.githubusercontent.com/assets/5135317/10467424/6e7c935c-71ae-11e5-8b92-897076baaf08.png)

As a result, the divider (`add |`) appears wider than it should be since the cell shows the word MISSING.

**Comment by percyliang** [comment]
1. All of these should be missing, except divider (handled separately).
2. Make MISSING less ugly.
