### ISSUE TITLE
edit / save doesn't return focus

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1337]
On master: if press 'e' to start editing a worksheet, then 'ctrl-enter' to save, then the cursor position vanishes and j/k don't work.  If click 'edit source' to edit a worksheet, then the cursor position still vanishes but the keys work.

Desired behavior: cursor position should be restored and the keys should work.

**Comment by kashizui** [comment]
Clicking on View after entering View Source doesn't work

**Comment by percyliang** [comment]
Fixed by the ace editor.
