### ISSUE TITLE
handle binary files in bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1347]
Currently, if we try to get the contents of a binary file, we throw an exception.
UnicodeDecodeError: 'utf8' codec can't decode byte 0x90 in position 24: invalid start byte

Should be able to get the binary contents, but on the interface, should not show the binary contents - just write '(binary file)'.  How to test for this?

**Comment by percyliang** [comment]
@kashizui: this is fixed, right?

**Comment by kashizui** [comment]
Yep! #1405
