### ISSUE TITLE
% title directive not recognized

### ISSUE THREAD

**Issue by pratiksha** [codalab/codalab#1353]
Worksheets do not recognize the % title directive, although it's mentioned in the tutorial at
https://github.com/codalab/codalab/wiki/User_CodaLab%20CLI%20Tutorial
Not sure if this is intended to be fixed by #1322, but it seems like it's not currently an available feature, so perhaps the tutorial should be changed in the interim.

**Comment by percyliang** [comment]
Documentation needs to be fixed.
