### ISSUE TITLE
schema tables cause worksheet rendering to break

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1357]
https://www.codalab.org/worksheets/0xb5e26409c926464dbd27eb7c0e9cf114/
https://www.codalab.org/worksheets/0xec2639e3bdb44febb46ce0d91797ff36/
Both of these are related examples that yield different errors, but are probably caused by the same root problem.

**Comment by kashizui** [comment]
@percyliang the error currently showing up in the console is actually due to the fact that these worksheets don't exist, do you have other worksheets that show this problem?

**Comment by kashizui** [comment]
@percyliang the error currently showing up in the console is actually due to the fact that these worksheets don't exist, do you have other worksheets that show this problem?

**Comment by percyliang** [comment]
No...if both of these worksheets don't exist and we have a good way of
showing non-existent worksheets, then just close the issue.
