### ISSUE TITLE
type shortcut to copy bundle uuid into action bar

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1376]
Use case: enter 'cl mimic' in action bar.
Then scroll around to the different bundles, and type 't' to copy the uuid into the action bar.
This makes it a lot eaiser to create new commands.
Should be able to type 't' from action bar too.

**Comment by kashizui** [comment]
@percyliang What do you mean exactly by args again?

**Comment by percyliang** [comment]
cl info -f args
