### ISSUE TITLE
cl upload on action bar

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1377]
This should not pop up anything but just execute the action but it currently pops up the upload dialog:

    cl upload dataset -c "hello"

This should select program rather than dataset in the popup:

    cl upload program

**Comment by kashizui** [comment]
In light of the recent changes, the new desired behavior is simply to immediately display the file browser when uploading a file. Using the `-c` flag should just execute immediately without firing a UI action.

**Comment by kashizui** [comment]
Fixed by codalab/codalab-cli#219
