### ISSUE TITLE
New deployment is not working

### ISSUE THREAD

**Issue by FlavioAlexander** [codalab/codalab#1395]
- @percyliang I tried your new configurations without any success. I can't figure out which of that many changes you made is causing the problem. Please take a look

![deployment](https://cloud.githubusercontent.com/assets/7468482/11076850/0d65dfbe-87cb-11e5-9d48-0ee5e6de8944.png)

**Comment by percyliang** [comment]
Hm works for me.  Can you give more details?  @stephenkoo can you try
deploying?

**Comment by kashizui** [comment]
I can give it a shot tomorrow

**Comment by kashizui** [comment]
From master (without merging from develop)?

**Comment by FlavioAlexander** [comment]
@percyliang The screenshot is all I have. @kashizui It is not a good idea to deploy to production. Lets have test server working first which uses develop branch
