### ISSUE TITLE
long commands on action bar get mangled

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1402]
Long commands that wrap around are not rendered properly, making it basically impossible to edit.

**Comment by percyliang** [comment]
This might be a tricky problem to fix.

**Comment by kashizui** [comment]
I feel like the jquery terminal plugin should be handling this correctly—it may just be a matter of using it correctly? Completely guessing though.

**Comment by percyliang** [comment]
In theory, yes...

**Comment by percyliang** [comment]
Fixed by #1482
