### ISSUE TITLE
In fig q program jobs are queued but not executed

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab#1404]
I have a problem with using q to run docker containers in CodaLab. I followed instructions on CodaLab's website how to install and use q. The problem is that jobs are queued but not executed. For example, running command "q -add ls /" shows the following status with "q -list":
J-yx0p2k ready ls /
As I understand when a job is finished its status should be "done". When I check output from "q -mode worker" terminal, there is no any update on the job status. It looks like a worker doesn't receive job info. Any help with this issue would be appreciated. Thanks.

**Comment by percyliang** [comment]
It seems like there's a problem with q more generally.  So just to confirm, independent of CodaLab, if you type the following in different terminals:

    q -mode master
    q -mode worker
    q -add ls /

then nothing runs?

**Comment by abmnv** [comment]
Yes, that is correct . This is on Azure VM running Ubuntu 15.04. Could this be a problem that certain ports are blocked by default Azure settings? thanks.

**Comment by percyliang** [comment]
Hm...I tried this on several Linux installations (Ubuntu 14.04, CentOS),
but I can't reproduce it.  Have you tried it on other Linux machines?  All
the instances of q are running on the same machine or not?  If they're not,
then it might be a port blocking issue.  From the worker machine try
'telnet <master> 7890' and see if you can connect.

 -Percy

**Comment by abmnv** [comment]
They are on the same machine. I will try telnet.

**Comment by abmnv** [comment]
This is what I get when I try to connect to local host:
azureuser@cbibop:~$ telnet localhost 7890
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=ISO-8859-1
Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
Date: Tue, 17 Nov 2015 15:47:29 GMT
Content-Length: 309
Connection: close

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Bad Request</TITLE></HEAD>
  <BODY>
    <H1>Bad Request</H1>
    bad Request-Line `'.
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08) at
     cbibop.cbibop.b1.internal.cloudapp.net:7890
    </ADDRESS>
  </BODY>
</HTML>
Connection closed by foreign host.

**Comment by percyliang** [comment]
Ok, so you're able to connect just fine then...I don't know what the
problem is then.  I would try it on a different machine and see if you can
reproduce it.

**Comment by abmnv** [comment]
Out of 4 Azure VMs that I have running, it works on only 1. Can you suggest any debugging steps? thanks.

**Comment by percyliang** [comment]
Show status of workers:
q -w -header

Show status of jobs:
q -l -header

Check that the resource requirements of the jobs are satisfied by the
workers.

**Comment by abmnv** [comment]
Does VM need more than 1CPU to run commands in q?

**Comment by percyliang** [comment]
No, it shouldn't.

**Comment by abmnv** [comment]
It seems like the only VM that runs jobs has 2 CPUs, all other VMs have 1CPU. I will try to increase the number of CPUs to check if that is the issue.

**Comment by abmnv** [comment]
After I increased it to 2 it works. Strange?

**Comment by percyliang** [comment]
The issue is with the memory.  By default, jobs demand 1.5GB of memory, so
if you don't have that much then, the job won't run.  You can change the
memory limit using -mem.  For example, do
q -add / -mem 100m

**Comment by abmnv** [comment]
ok, it makes sense now. thanks.
