### ISSUE TITLE
Jobs hang up with cl run command

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab#1416]
I am trying to run jobs with "cl run" command. I checked that fig/q can run jobs by itself without problems. However, when I try to run a cl command jobs hang up with status "assigned" but nothing happens. Here is an output from "q -mode worker" terminal:
```
azureuser@cbibop:~$ q -mode worker
===== worker v76 cbibop-em, basePath = scratch
/home/azureuser/fig/bin/q -mode worker
======= Running job J-zupucf
Creating scratch/home/azureuser/.codalab/temp
Need /home/azureuser/.codalab/temp/0xf7bb5a3f9a194452bd776cc65aaf8f2a [ 1447868855]
Need /home/azureuser/.codalab/temp/0xf7bb5a3f9a194452bd776cc65aaf8f2a.sh [ 1447868855]
Need /home/azureuser/.codalab/temp/0xf7bb5a3f9a194452bd776cc65aaf8f2a.sh [ 1447868855]
Running job J-zupucf (pid ): time 4s, mem -1m, disk 1m
```

Here is an output from q -list command:
```
(venv)azureuser@cbibop:~/codalab-cli$ q -list                                                           
J-39khve  cbibop-89 cbibop.cbibop.b1.internal.cloudapp.net  assigned      364d23h  -1m  -1m  temp  bash home/azureuser/.codalab/temp/0x5e...ca19384ea1d.sh use_script_for_temp_dir
```
Thanks,

**Comment by percyliang** [comment]
Can you check that you an ssh from the machine to itself and that docker
works (docker run -ti codalab/ubuntu:1.9 bash)?

**Comment by abmnv** [comment]
I can ssh to itself with a password. I am getting this line from "q -mode master" terminal:
```
rsync -arz -e ssh -o StrictHostKeyChecking=no --delete /home/azureuser/.codalab/temp/0x992f775d89fc4b44b48fdb59c7ad3b6e azureuser@cbibop.cbibop.b1.internal.cloudapp.net:/home/azureuser/scratch/home/azureuser/.codalab/temp
azureuser@cbibop.cbibop.b1.internal.cloudapp.net's password: localhost - - [19/Nov/2015:20:55:51 UTC] "POST / HTTP/1.1" 200 1587
```
Is the problem that it can't ssh without password? 

The docker works fine.

**Comment by percyliang** [comment]
You need to ssh into the machine without a password (set up ssh keys for
that).

**Comment by abmnv** [comment]
After running for a while in "cl work-manager -t q" terminal a job status is changed to 
`'failure_message': u'Exit reason: Unable to copy'`

**Comment by abmnv** [comment]
Thanks, it works now. It would be nice if this step was documented in Installation instructions. It is not mentioned anywhere.

**Comment by percyliang** [comment]
Good idea to update the instructions.  Could you remind me the list of all
things you did to make things work?

**Comment by abmnv** [comment]
Sure, here it is:
1. Azure VM needs at least 2GB of memory to run jobs with fig/q. 
2. A VM should be able to ssh to itself without password to run jobs with cl.

**Comment by percyliang** [comment]
I updated the Wiki:
https://github.com/codalab/codalab/wiki/Setup-Local-Worksheets#workers

**Comment by abmnv** [comment]
I checked the wiki. It says that the minimum requirement for q is 1.5GB of memory. I think it is more than that because I had  A1 configuration for Azure VM with standard tier which has 1.75 GB memory and it didn't work. It started working after I switched to A2 configuration which has 3.5GB of memory.

**Comment by percyliang** [comment]
It's 1.5 GB free.  Updated wiki to clarify.

**Comment by abmnv** [comment]
Thanks.
