### ISSUE TITLE
Worksheet interface should still allow editing even if rendering fails

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab#1424]

**Comment by percyliang** [comment]
This is to make the worksheet interface more robust against errors in the
user's worksheet.  It shouldn't fail but print a nice error, but if it does
fail, we should catch the exception and allow user to modify their
worksheet.

**Comment by kashizui** [comment]
Certain errors are still very difficult to recover from (binary decoding at the JSON encoding stage), because we can't even get metadata about the worksheet. Working on a solution for recovering from less fatal problems, assuming these deeper issues should never show up once we've dealt with them.

**Comment by kashizui** [comment]
This will actually entail better error recovery/reporting infrastructure when interpreting/rendering a worksheet—how do we throw an error in the middle of interpreting a worksheet while still responding with a valid basic worksheet info scaffold that the frontend can work with?

**Comment by percyliang** [comment]
Currently, we just render errors inside the worksheet...we just have a
markup interpreted items that prints out the error message.  (Can we make
this big and red?)  This is the main case to guard against.  Should be
consistent with 'cl print' too.
