### ISSUE TITLE
Create ability to form teams

### ISSUE THREAD

**Issue by loriada** [codalab/codalab#323]
Teams allow competition participants to work together which is how many participate today.
Teams will also allow sharing between a smaller group in experiments.

**Comment by xbaro** [comment]
I was working on that, but I'm still knocked by my job projects. My Idea to do not have problems with previous competitions was to just create the teams on the DJango models, and do not affect the Cli. It can be managed by grouping leaderboard  by group affiliation when showed the results, showing the team name together with the user or just hide the user name when it is in a team. At the end all users should be able to submit results, but only the best one is considered for final ranking. The only problem is with hidden leaderboards, where we need to specify if one of the members of the team have priority over the others, to just take into account one of them and not the best one, to avoid big teams to have more changes to win by submitting many results.
