### ISSUE TITLE
Adjust bundle service API to meet web site needs

### ISSUE THREAD

**Issue by cpoulain** [codalab/codalab#348]
This is a somewhat open-ended issue to keep track of implementation changes in the bundle service API in order to satisfy the needs of the web site.

**Displaying list of worksheets and individual worksheets**

See issue #309 for a discussion about what information the web site needs for rendering list of worksheets and individual worksheets.

**Comment by Raisins** [comment]
closing. CLI/Worksheet/bundle services is integrated.
