### ISSUE TITLE
Default Worksheets

### ISSUE THREAD

**Issue by zyskowski** [codalab/codalab#419]
Every user when registered should have a default worksheet created for them.  The "no bundle left behind" principle is desired to ensure we don't have cases where bundles are created without the ability to delete/manage properly.

		○ Default worksheets
			§ Need one for every auth user
			§ Bundle creation/editing requires attachment to a worksheet
			§ Bundles will be ref counted for use by multiple worksheets without duplication of the bundle (ensures version control)
			§ "No bundle left behind"

**Comment by ErickWa** [comment]
Replaced by newer ticket
