### ISSUE TITLE
Add support for multiple active phases in a competition

### ISSUE THREAD

**Issue by cpoulain** [codalab/codalab#450]
We received the following feedback:

> We have entered the evaluation phase of our spine challenge, and I noticed that the training phase is closed automatically. I didn't know this would happen and I think in many cases this might not be the wanted behavior. The thing is that one might want to still experiment with algorithms and parameter settings and for that it would be great if one can still submit updated results on training data even when the challenge is open for evaluation on test data. This is particularly true for challenges that run for long times as new participants might join much later.
>
>In our case, I have now reset the evaluation phase date to keep the training phase open for another week. However, there seems to be no option to keep both phases alive.

The current behavior assumes that phases in a competition happen sequentially. At most one phase is active at any given time. As far as I know, there are no fundamental assumptions built into the system that would prevent the behavior described above. Each phase would need to have its end-date specified in a more explicit way: 1) ends when next phase starts (would be default for backwards compatibility); 2) ends at specific date; or 3) never ends.

The current workaround would be to create multiple competition since the last phase of the competition can be configured to never end.

**Comment by ErickWa** [comment]
Closing very old backlog issue that has since been addressed
