### ISSUE TITLE
Python upgrades

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#504]
Here is a user request I received:
Would it be possible to install scikit-learn 0.15 in codalab's servers? Some routines I use don't work properly on 0.13.

We have an old version of Python and libraries on Codalab (more than a year old). But upgrading is almost impossible because we do not have any backward compatibility plan (changing version would make older programs not work anymore). We need to make a plan for the future. Given what you know of the system, what suggestions do you have?

**Comment by ErickWa** [comment]
Upgraded to Anaconda.
