### ISSUE TITLE
Use competition form to create competition

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#505]
First time users are confused by competition.yaml, and if they don't fill it out properly they don't get any feedback. For example, if you upload a competition with a faulty yaml file you get "Oops, something went wrong."

A big concern is making a form for leaderboard results.

We should refactor the work flow to allow creating a competition using the easy to understand form.

**Comment by ErickWa** [comment]
Needs a User Story for how this might work.

**Comment by ErickWa** [comment]
Closing as duplicate w/ #851
