### ISSUE TITLE
HTML report bug

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#788]
There is a feature in the YAML file
enable_detailed_results: True         
The scoring program can produce an html file and if enable_detailed_results is true, the file is displayed in the leaderboard.
See this issue:
https://github.com/codalab/codalab/issues/581
"Check if the output folder contain an "html file" and copy the html file as detailed_results.html"

PROBLEM: In codalab.org, the contents of the html file is shown as regular text, the html tags are ignored. See for instance https://www.codalab.org/competitions/2321#results

This is particularly a problem because we want to show figures (learning curves). Can you fix this and also make an example of how to include figures. I got the instructions "include images as Base64 text", what does this mean?

**Comment by ckcollab** [comment]
TODO: Pragnya to add wiki entry detailing how to use this.

**Comment by ckcollab** [comment]
Detailed results page docs:
https://github.com/codalab/codalab/wiki/User_DetailedResultsPage
