### ISSUE TITLE
Learderboard hiding bug

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#790]
There is a feature that is no longer working:
![image](https://cloud.githubusercontent.com/assets/7594063/5385522/08f3c29e-8091-11e4-8833-f938c7618f06.png)
There is a menue that allows you to hide the leaderboard results:
![image](https://cloud.githubusercontent.com/assets/7594063/5385538/3238ef3a-8091-11e4-93a8-f88dda9f655a.png)
But when it is active, the results are still shown on the leaderboard.

It would be great to make that work again because sometimes when a "final" phase starts it takes a loooong time before the all results are computed (and possibly verified). It is best to wait until everything is ready, then show the whole result table. Thus we need to hide the leaderboard and let the organizers switch to showing the results when everything is OK.

**Comment by ckcollab** [comment]
It appears that the leaderboard is still visible as long as you are the owner, it is not visible to participants in the competition!
