### ISSUE TITLE
web worksheet editor broken

### ISSUE THREAD

**Issue by tachim** [codalab/codalab#792]
Typing things into the editor windows will frequently send me back to the previous page or have some other unintended effect (like closing editing mode and losing my changes). It might be interpreting the things I type into text boxes as keyboard shortcuts for the editor - those should be disabled if the cursor is focused in a text box.

**Comment by ErickWa** [comment]
Hi Tudor,

Can you help us with repro steps?  Otherwise I'll have to close this issue as we're unable to reproduce it.

Thanks, -- Erick

**Comment by tachim** [comment]
Hi Erick - sorry, I didn't see the notifs for this issue. I haven't seen these problems recently so they were probably fixed in some commit. Closing for now.
