### ISSUE TITLE
Identical versions of Python on competition and worksheet sides

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#797]
On the competition side we run the latest version of Anaconda to make sure the competition participants can easily reproduce on their local machine a standard installation. Could we have the same version on the worksheet side to allow them to use worksheets?

**Comment by percyliang** [comment]
The competitions side should use docker (for example, the standard instance https://hub.docker.com/r/codalab/ubuntu/).  The worksheets side can use any version of any program as long as it is in a docker container.
