### ISSUE TITLE
User management of competition submission bundles via "My datasets"

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#802]
Right now, competition participants who submit code do that in each competition via the submission page. All users also have a "My Dataset" space where they can submit bundles. This is at the moment only used by organizers. I suggest to make this also available to participants. In this way, they can first submit their code to "My Datasets", then submit to the competition a reference to the uploaded bundle. This would allow them to manage revisions of their code and eventually re-submit older versions.

Ideally, the management of code bundles should be uniform between worksheets and competition.

**Comment by ErickWa** [comment]
Issue closed and has been subsumed by new approach in how the CLI functions.
