### ISSUE TITLE
Issue viewing extra HTML details sometimes

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#805]
"The 'view detailed results'-screen seems to be broken:

        <Error><Code>
AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
        RequestId:69d69a31-0001-0018-2752-9cf545000000
        Time:2014-12-10T16:54:01.2257588Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>"

**Comment by ErickWa** [comment]
Needs further examples / documentation. Tied to HTML issue that Pragnya is working on.

**Comment by ckcollab** [comment]
I'm marking this as closed until we get this error again.
