### ISSUE TITLE
Number participants

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#819]
In https://www.codalab.org/my/competition/xxxx/participants/
we have a table of participants. In would be great to have the lines numbered and/or get a count of the number of lines so we can know the number of participants.

**Comment by ErickWa** [comment]
Add a Line Number to the Participants List so that Organizers know how many participants are in a competition.

Also add a Date Stamp to each Participant so you know when they joined a competition.

**Comment by ErickWa** [comment]
Need Grand Total number of submissions (not per participant on Leaderboard)

Ideally, should number the submissions per phase as well, so we can see how many submissions per phase.

**Comment by ErickWa** [comment]
Number of lines completed; Number of submissions yet to be added

**Comment by ErickWa** [comment]
Related to #916
