### ISSUE TITLE
MathJax $\sum_z p_\theta$ doesn’t render in math

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab#855]
Everything else you throw at mathjax renders. Not sure why this doesnt.

**Comment by Raisins** [comment]
This fails due to markdown and mathjax bumping heads and rendering over each other. 
It reads  `_z p_` as _z p_ with italics which is `<em>z p</em>` as you can see in this sentence. Then mathjax tries to render and since the `_` are gone can't turn it in to math.

**Comment by Raisins** [comment]
Saving this link for later, Was able to reroute the render. 
https://github.com/kerzol/markdown-mathjax

**Comment by Raisins** [comment]
After fighting mathjax.que and markdown render most of the day. A dirty but better solution showed up and this should be fixed to test you can create a worksheet like this 

```
#Testing mathjax

$\sum_z p_\theta$ 
$x^2$

$\frac{1}{\pi}$

$\frac{2}{25}$

$u^2 + 32*2$
```

**Comment by percyliang** [comment]
Awesome - thanks!
