### ISSUE TITLE
after save a text element with math, MathJax doesn't re-render

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#865]
In the worksheet interface, when you edit a block and put some math (e.g., '$x^2$') and save, the math doesn't render.  (Need to refresh page again for the rendering to happen).

**Comment by Raisins** [comment]
What browser are you using and are you running local? Below gif is in firefox on OSX. It also works the same on chrome. I am not seeing this issue locally or on test evn. 

![mathjax](https://cloud.githubusercontent.com/assets/123099/6114031/2ea9b9fa-b050-11e4-8ff7-05a99fe0e08e.gif)
 

Can you tell me what you console is saying. Right click inspect element, then click on the console tab.
