### ISSUE TITLE
action bar run command not working

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#866]
Typing
/ run (enter) date (enter) (control-enter)
doesn't do anything.

**Comment by Raisins** [comment]
You have to wrap a command in single quotes

/ run (enter) 'date' (enter) (control-enter)

The quotes tell the front end you are doing a command.

**Comment by percyliang** [comment]
Still doesn't work, even with quotes.  (Without quotes worked before.)
This is on Linux Firefox.

**Comment by Raisins** [comment]
This seems to be an issue with the new worker setup. `Illegal metadata keys:`

**Comment by percyliang** [comment]
I made some changes on the backend that invalidated some metadata keys.
The frontend should just ignore metadata keys which are not in the schema.
