### ISSUE TITLE
render links in tables

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#875]
In a table on the worksheet page, in the interpreted items, the post-processing function can be 'link'.  If so, then render the value as a hyperlink.  If the post func is 'image', then render the value as an image.

**Comment by Raisins** [comment]
Do you have an example raw `%display table` I can work off of for links and images in a table. I do not know how to do that in the cli.

**Comment by percyliang** [comment]
% schema s1
% add stdout /stdout link
% display table s1
<put some run here (e.g., cl run date)>

Let's punt on the images for now.

**Comment by Raisins** [comment]
relied on pull https://github.com/codalab/codalab-cli/pull/28 from the cli
