### ISSUE TITLE
Create a prep_for_offline management command. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab#896]
Mathjax, Less and others can take a long time to copy or download when deploying or settingup a new project. Since adding all of mathjax to make sure rendering is correct in many browsers. The project is very bloated. 

Lets add a `prep_for_offline` management command that would:
 -  [x]  compile less to css
 -  [x]  download mathjax and it's required fonts/pngs and put them in the correct folder structure
 -  [x] have a settings bool to load said files
 -  [x] print out what settings to change. to account for the new downloaded files. 

other things that need done in this ticket
  -  [x] Remove all of mathjax and go back to CDN (unless you ran prep and changed settings)
  -  [x] clear out git history of mathjax

**Comment by Raisins** [comment]
I have removed mathjax. 
Please @percyliang  @adamtlord  @ckcollab do a `git rebase` or check everything out clean or it will come back.

**Comment by Raisins** [comment]
Git repo size is still nearly 50mb. (but is same size as it was before all this) 
This is do to some legacy files in the history.  Running this script. 
https://stubbisms.wordpress.com/2009/07/10/git-script-to-show-largest-pack-objects-and-trim-your-waist-line/

```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size  pack  SHA                                       location
3773  401   c0863e413f7f30903a42231969e1fec89b953fc2  bundles/pliang/uci_arff/kdd_ipums_la_99-small/data.arff
2750  354   d134d1bfeb191aa30d4a56c474ea46d01ba051f2  bundles/pliang/uci_arff/kdd_internet_usage/data.arff
1641  668   67aa8d7cb0ceb13b2529751214cc111a53f24dd2  bundles/pliang/uci_arff/mfeat-fourier/data.arff
1445  656   3192269a3d353e8867f5ebb32794739a6ae9fcc1  bundles/pliang/uci_arff/mfeat-karhunen/data.arff
1440  567   6f74a29bdb64739ad8980d2e5e38a80d90e39808  bundles/pliang/uci_arff/mfeat-factors/data.arff
1109  536   0426d02a56a107df89ff5962fe84f952ec233aa0  bundles/pliang/uci_arff/mfeat-zernike/data.arff
1101  177   764e399d7a9af8937eec771534cc7210eaeefa79  bundles/pliang/uci_arff/kdd_UNIX_user_data/data.arff
1054  343   53f89bbc7bcf51511aef4b2ac4ac1303b67bfb0d  bundles/pliang/uci_arff/waveform-5000/data.arff
1039  41    161dcc37948a2416ab9520da7cf6c2a80e6399ac  bundles/pliang/uci_arff/nursery/data.arff
1010  867   f4cf1c73c0a9ba90b0498982e24cd26c6f28dcc1  docs/codalabstyleguideandcomps.pdf
```

**Comment by percyliang** [comment]
Thanks, Francis!  Is it easy to remove the uci_arff files too?  Someone
added them by accident.  If not, I guess it's okay...

 -Percy

**Comment by Raisins** [comment]
Closing this an adding a new ticket for cleaning those out.
