### ISSUE TITLE
More information saved when signing up

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#905]
![image](https://cloud.githubusercontent.com/assets/2185159/6563840/99c9adea-c661-11e4-8672-a22e4e8c7cb1.png)

## Signup form

Required fields to be added:
- [x] Team Name
- [x] Method Name
- [x] Method Description

Optional fields to be added:
- [x] Affiliation
- [x] Project URL
- [x] Publication URL
- [x] Bibtext

- [x] Saving hooked into allauth

## Profile detail

Link to profile detail from:
- [x] competition leaderboard
- [x] participants tab
- [x] submissions tab

Profile detail page:
- [x] Lists all details from profile with nice bootstrap table

- [x] Edit new profile details on existing settings page

**Comment by ErickWa** [comment]
Pushed to production...
