### ISSUE TITLE
Make it possible for Contest Organizers to see current Rankings from Scoring Program

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#908]
Requested by Isabelle:

* User submits new entry
* Scoring program scores entry and returns a result for output to the leaderboard

This is the current functionality.  Additional functionality required is:

* Scoring program should not only be aware of a discrete submission output, but should also have logic that compares this new output to the leaderboard, and performing an additional calculation to see how much better or worse this output is, and then award "Points" based upon the different scores.

* Leaderboard automatically re-calculates points for all entries based on relative impact of a new output.

Compare this to current functionality in which scoring program operates independently of leaderboard.

Also need to define how "points" work, and how the leaderboard changes over time

Refer to "Coopetition Points System" for more details

**Comment by ErickWa** [comment]
Related to Task #909

**Comment by ckcollab** [comment]
Use "Download as CSV" information and send that to scoring program
