### ISSUE TITLE
Usernames

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#912]
It seems when my username is X@a.com I can login also by providing just X as login and this one (X) displays as well in the autocomplete (for example when adding admins).

I registered lukasz.romaszko@qqq111qqql.com as email and username, in the autocomplete is used a full username with @ (even though this address does not exist, so cannot 'confirm' and login [sub-issue1])

The problem is when I register as X@a.com, worksheets do not allow names with '@', so I cannot connect to server (cl work). Percy suggested that usernames should do not allow for '@'  (and any other special characters) [sub-issue2].
Turning off special characters during registration will solve the problem, but what with users already registred who use them [sub-issue3].

**Comment by ErickWa** [comment]
Fixed via other username changes that were pushed for worksheets.
