### ISSUE TITLE
Default worksheets on CodaLab Test default to Public Viewable

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#931]
Strange behavior: Contestants from MS Coco on codalab.org have corresponding publicly available worksheets on codalabtest.cloudapp.net.

![image](https://cloud.githubusercontent.com/assets/4361560/6833363/9889bd3c-d2e9-11e4-8dfe-1cfd6caf7fac.png)

**Comment by Raisins** [comment]
If they are signing up on the test env as well. We create a worksheet on sign up. Also with Percy's semi recent change to worksheets, all new worksheets default to public. 

If they are not signing up on test, then this is a weird problem and should not be happening.

**Comment by ErickWa** [comment]
Hi Francis,

Evelyne feels very strongly that this should not be happening and that the worksheets should not default to being publicly visible like this.  Is this something that Percy insisted on?

Thanks, -- Erick

**Comment by Raisins** [comment]
Yes, this is a backend cli permission change and was a percy design decision.  Alternatively if default public is a system that the cli feels strongly about default public we can visit the codalab web setting permission to private.

**Comment by percyliang** [comment]
The motivation was GitHub: things are public by default, which I think
encourages more of an open community spirit, rather than having people
working in isolated silos.  Of course, we can make it easy for people to
make things private if they choose.  In any case, having more things public
means that we have to work a bit harder on search and making sure people
see the right information.

**Comment by evelynev** [comment]
The search functionality will not help reduce the noisiness of coming across 'content-free' worksheets.
If a worksheet is created at registration time, imagine a competition with over 200 participants (e.g. AutoML has currently over 250) and as many “empty” worksheets created. 
The incentive to make worksheets available to all will come not from forcing people to do so but from putting in place the right incentives (e.g. rewarding open contributions). We do not want people to see worksheets being created without them realizing they will appear on the website visible to everyone or without them having a chance to expose a worksheet they are happy to expose.  The worst thing which could happen is that people see their ‘empty’ worksheet, don’t have time there to create content, delete them and now we’re making it difficult for them to come back and create one.

Having said that, I agree CodaLab should encourage the community to share by making it easy to do so. My recommendation is  to indeed create worksheets at registration time as private by default but inform the user they can make them public right away and also making it very easy to publish worksheets later when they are ready to do so.

**Comment by ErickWa** [comment]
Hi Percy, can you give us some feedback on Evelyne's comments above?

**Comment by percyliang** [comment]
I understand the concern.  We should change it so that by default, new
users do not get a home worksheet.  They have to explicitly create it (via
'new').

 -Percy

**Comment by percyliang** [comment]
This should be fixed by #968
