### ISSUE TITLE
search directive

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#933]
Not supported right now (just prints out the string 'search').
Should support this.
Examples:
% search type=run
% search .count

**Comment by Raisins** [comment]
Turns out to be complicated due to sub types that search returns.  Opened a PR to track. 
In your example  `% search type=run` returns table `% search .count` just the number
@percyliang is there more then a table or a simple markdown?

**Comment by percyliang** [comment]
The return type is always just a number of a list of bundle infos.  If it's
a number, then it can just be printed inline (just like % display inline).

**Comment by Raisins** [comment]
Almost done. Needs styled and has a weird bug about moving around other search bundles. Going to get @adamtlord quick help on that front and for a 2nd pair of eyes. Then merge it in
