### ISSUE TITLE
action bar focus can't escape out after entering command without clearing everything. 

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#938]
Type
/ (to focus on action bar)
`escape` (to focus on main page)
E (to edit worksheet)
Focus goes to the action bar and an 'E' gets typed.

**Comment by Raisins** [comment]
This is an usability pattern  with the nature of the action bar and it's fancy autocomplete commands nature. You have to double tap escape. Once to escape the fact you are typing something it is listening to and agin to escape the bar for real. 

The reason for this is if you are typing something with autocomplete. Say doing an info command and you start to type 'ml-c' there are a lot of things that start with ml-c but you realize this is a mistake you wish to start over. Hitting escape will clear out what you typed.  This is a feature of select2 which we are using for action bar.  

**There is a bug here**. If you have a command entered 'info' and start to enter something you can not escape by hitting `escape`  no matter how much you do you must either delete the command then hit `escape` or click off.
