### ISSUE TITLE
automatically show action bar when display a worksheet page

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#939]
Otherwise, it's not clear how you get there ('/' is not obvious).

**Comment by Raisins** [comment]
It's behavior right now is  shows if you have edit permissions hides if you don't. Because it is full of actions about that worksheet and if just viewing you can't do most of them.

**Comment by percyliang** [comment]
There are many things like jumping to bundles / other worksheets that you
want to be able to do anyway.

The desired behavior should be: always show action bar.  If you don't have
edit permission, don't allow the actions that require edit permission (add,
run, upload).
