### ISSUE TITLE
bundle info should show dependencies properly

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#941]
Current behavior: shows UUID and path
Desired behavior: what you get with cl info
<key>: <bundle name>(uuid)[<child path>]

Also, when there are no dependencies, nothing should be shown.  Currently, shows 'none: none'.

**Comment by Raisins** [comment]
Updated bundle page to show all things cli shows. I also reordered them so you can easily see the correlation with the files (in the file browser) and how the are part of the dependencys

![screen shot 2015-04-08 at 1 30 33 pm](https://cloud.githubusercontent.com/assets/123099/7054769/9c9a340a-ddf3-11e4-94ad-bb95e5931a0b.png)
