### ISSUE TITLE
fields on the bundle details page missing

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#943]
Should display other fields (e.g., data_hash, owner, etc.)
Should display host_worksheets.
Should display permissions.

Basically, things should match 'cl info -v' the command-line.

**Comment by Raisins** [comment]
Removed bug. As this is a features. Host_worksheets and a formatted permissions information is not returned by get_bundle_info or metadata lookups currently.

**Comment by percyliang** [comment]
It is included - just set the flag to fetch host worksheets.  Check out the
cli.
