### ISSUE TITLE
display permissions of worksheet

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#959]
Currently, only a worksheet shows only 'Permission: read|all', which is the user's permission on the worksheet.  Instead, we need to display which groups have permissions on this worksheet (what is shown in cl wls).   In particular, the user we should be able to see if this worksheet is public or not.

What should be displayed:

Owner: codalab
Permissions: public(read), mygroup(all)

**Comment by Raisins** [comment]
We are showing all groups even if you are not a part of it. This might be a privacy concern. 
![codalab_-_worksheet_details](https://cloud.githubusercontent.com/assets/123099/7421695/bba7559a-ef3b-11e4-9958-86f313b99b71.png)

**Comment by percyliang** [comment]
How was this fixed?  It should be fixed on the CLI side...

**Comment by kashizui** [comment]
Fixed on CLI side by https://github.com/codalab/codalab-cli/pull/164
