### ISSUE TITLE
restrict usernames

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#967]
Only allow usernames to be ones that match spec_util.NAME_REGEX, because people's default worksheet needs to be their username, and worksheet names cannot be arbitrary.

**Comment by Raisins** [comment]
Rather then arbitrarily limit usernames across codalab. Which will be frustrating to a user. Lets strip out things that are not allowed in a worksheet. I was doing a version of this before with automatic creation of worksheets. 

https://github.com/codalab/codalab/blob/master/codalab/apps/authenz/views.py#L44

**Comment by percyliang** [comment]
I think it's much better and simpler to have consistency between usernames
and worksheets.  We need to have restrictions on the username anyway (e.g.,
no spaces), so we let's not have extra logic that strips out things.  With
stripping out, you might get two unique usernames mapping to the same
worksheet name, which would be bad.
