### ISSUE TITLE
displaying search directive

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#974]
Ideally, the table displayed by the search directive would look exactly like a normal table.  At minimum, it should have links on the bundles that are clickable.

**Comment by Raisins** [comment]
The infomation given back from search does not contain the uuids. Currently returns these fields. 

```
"name",
"description",
"bundle_type",
"created",
"dependencies",
"command",
"data_size",
"state"
```

**Comment by percyliang** [comment]
Fixed.
