### ISSUE TITLE
render cl in action bar's returned results in a modal. Removing alert. 

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#979]
Currently, we're using alert(...), which has two problems: (i) it is an annoying popup, (ii) can't control the font.  The information should be shown in a monowidth font and appear on a message panel of some sort in the corner.

**Comment by Raisins** [comment]
Will add a dynamic modal to the page for this and other results.

**Comment by Raisins** [comment]
put in some ground work for the modal. 
https://github.com/codalab/codalab/commit/aece6b5
putting this ticket on hold, till we decide what to do with action bar.
