### ISSUE TITLE
Duplicate competitions listed in "Competition's I am running"

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab#986]
Reported by @madclam, not experiencing it myself and not a breaking bug but making a record here just-in-case!

**Comment by lr292358** [comment]
I experienced it too -- I thought that maybe the reason is that I might be also listed as 'admin' in my own competition (which was sometimes the case), but I wasn't in this competition, so don't know the reason.

**Comment by ckcollab** [comment]
Are there still duplicates even today Lukasz? I believe this may have been fixed along with competition sorting on admin screen.

**Comment by lr292358** [comment]
yes there are duplicates on codalab; and sorting is not pulled on codalab. Please pull on codalab.

**Comment by lr292358** [comment]
IDs of my duplicated competitions are are 3311 and 3301, this might be caused when something was broken earlier because it does not happen since 2 months
