### ISSUE TITLE
Sharing features and metrics - improve competition public submission board

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#988]
Improve competition public submission board:
- add 'force sharing' (all submissions are public), 'block un-sharing' (users cannot hide after they shared) options in the competition editor.
- add score display in table (leaderboard and public submissions).
- administrators can add/remove public submissions.
- editing submissions comments.
- count number of downloads and show in table [allow only verified competition participants to download].
- add “likes/thanks/thumbs up” at particular submission in public submissions and display the number of thanks.

**Comment by lr292358** [comment]
Scenario for force sharing?

**Comment by ckcollab** [comment]
Note: 'force sharing' will need a bit more discussion before we begin on implementation.

**Comment by madclam** [comment]
Force sharing is for use in the context of bootcamps. It makes sense in this setting to impose to all users to share their code so everyone can immediately learn from others.
Similarly to the fact that we have "force submit to leaderboard", we could have a "force sharing" that can be turned on or off.
Force sharing was used by Balasz Kegl in bootcamps he organized with success.

**Comment by ErickWa** [comment]
This issue unblocks Lukasz

**Comment by ckcollab** [comment]
These features are turning out bigger than I initially thought, I believe I'll have likes/thanks done soon but we should track each feature individually.

**Comment by lr292358** [comment]
I split this issue, so close this one.
