### ISSUE TITLE
Log of competition events

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#989]
Log all events of submission, sharing time (important), leaderboard scores for all users and include time stamps. 

Include also access to previous rounds (e.g. scores obtained from sharing codes -> used in to the final phase on the test set). This will be used to compute various coopetition metrics. Make this available to the scoring program. Extends: https://github.com/codalab/codalab/pull/984

**Comment by ErickWa** [comment]
This issue will unblock Lukasz

**Comment by lr292358** [comment]
Specification of the log:
Sharing times, un-sharing times, submission times, scores

Access to the numbers from the public submission panel (likes number, download number)
(can be in a separate file)

**Comment by ckcollab** [comment]
Example output:
```csv
pk,when_made_public,when_unmade_public,started_at,completed_at
130,,,,
137,,,,
138,,,,
139,,,,
140,,,,
141,,,,
142,,,,
143,,,,
144,,,,
145,,,,
146,,,,
147,,,,
148,,,,
149,,,,
150,,,,
151,,,,
152,,,,
153,,,,
158,,,,
159,,,,
178,2015-05-27 06:19:34+00:00,2015-05-27 06:19:35+00:00,,2015-05-27 06:19:35+00:00
179,,,,
187,,,,
188,,,,
200,,,,
241,,,,
247,,,,
248,,,,
249,,,,
325,,,,
369,,,2015-05-27 06:04:58+00:00,2015-05-27 06:04:59+00:00
370,,,2015-05-27 06:10:01+00:00,2015-05-27 06:10:01+00:00
372,2015-05-27 06:14:26+00:00,,2015-05-27 06:11:36+00:00,2015-05-27 06:14:26+00:00
373,,,2015-05-27 06:15:05+00:00,2015-05-27 06:15:06+00:00
```

**Comment by lr292358** [comment]
[] access to previous rounds (to access e.g. the final ranking). I think that can be just an access to a log in 2 files, like phase_0_log, phase_1_log

[] If submission fails, it is not included in the log

**Comment by ckcollab** [comment]
@lr292358 please add new details to the PR and we can track it there, getting kinda confused with all the checklists (although they are helpful!) :)

I'm responding to these in the PR

**Comment by ckcollab** [comment]
@lr292358 sorry I wasn't thinking properly, that PR is closed now, am starting a new one using this issue: https://github.com/codalab/codalab/pull/1074

**Comment by lr292358** [comment]
scores should be in the same file

**Comment by ckcollab** [comment]
- [ ] Scores should include those not on leaderboard as well

**Comment by ckcollab** [comment]
Pushed "all submissions included in scores" fix, lemme know how it works!

**Comment by lr292358** [comment]
=====================

LOG GOOD, CLOSED

=====================
